services:
  aerail:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aerail
    environment:
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      trains__bootstrapServers: ${TRAINS_BOOTSTRAP_SERVERS}
      trains__username: ${TRAINS_USERNAME}
      trains__password: ${TRAINS_PASSWORD}
      trains__certificatePath: ${TRAINS_CERTIFICATE_PATH}
      trains__topic: ${TRAINS_TOPIC}
      trains__consumerGroup: ${TRAINS_CONSUMER_GROUP}
      postgres__connectionString: ${POSTGRES_CONNECTION_STRING}
      NationalRail__BaseUrl: ${NATIONAL_RAIL_BASE_URL}
      NationalRail__ApiKey: ${NATIONAL_RAIL_API_KEY}
    ports:
      - "${WEB_PORT}:5000"
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: aeraildb
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - "${PGDATA_DIR}:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4:9
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - "${PGADMIN_DATA_DIR}:/var/lib/pgadmin"
    restart: unless-stopped


